/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as CConnectionIdRouteImport } from './routes/c.$connectionId'
import { Route as CConnectionIdDumpsRouteImport } from './routes/c.$connectionId.dumps'
import { Route as CConnectionIdIndexesRouteImport } from './routes/c.$connectionId.indexes'
import { Route as CConnectionIdKeysRouteImport } from './routes/c.$connectionId.keys'
import { Route as CConnectionIdOverviewRouteImport } from './routes/c.$connectionId.overview'
import { Route as CConnectionIdTasksRouteImport } from './routes/c.$connectionId.tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const CConnectionIdRoute = CConnectionIdRouteImport.update({
  id: '/c/$connectionId',
  path: '/c/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CConnectionIdDumpsRoute = CConnectionIdDumpsRouteImport.update({
  id: '/dumps',
  path: '/dumps',
  getParentRoute: () => CConnectionIdRoute,
} as any)
const CConnectionIdIndexesRoute = CConnectionIdIndexesRouteImport.update({
  id: '/indexes',
  path: '/indexes',
  getParentRoute: () => CConnectionIdRoute,
} as any)
const CConnectionIdKeysRoute = CConnectionIdKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => CConnectionIdRoute,
} as any)
const CConnectionIdOverviewRoute = CConnectionIdOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => CConnectionIdRoute,
} as any)
const CConnectionIdTasksRoute = CConnectionIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => CConnectionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/c/$connectionId': typeof CConnectionIdRouteWithChildren
  '/c/$connectionId/dumps': typeof CConnectionIdDumpsRoute
  '/c/$connectionId/indexes': typeof CConnectionIdIndexesRoute
  '/c/$connectionId/keys': typeof CConnectionIdKeysRoute
  '/c/$connectionId/overview': typeof CConnectionIdOverviewRoute
  '/c/$connectionId/tasks': typeof CConnectionIdTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/c/$connectionId': typeof CConnectionIdRouteWithChildren
  '/c/$connectionId/dumps': typeof CConnectionIdDumpsRoute
  '/c/$connectionId/indexes': typeof CConnectionIdIndexesRoute
  '/c/$connectionId/keys': typeof CConnectionIdKeysRoute
  '/c/$connectionId/overview': typeof CConnectionIdOverviewRoute
  '/c/$connectionId/tasks': typeof CConnectionIdTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/c/$connectionId': typeof CConnectionIdRouteWithChildren
  '/c/$connectionId/dumps': typeof CConnectionIdDumpsRoute
  '/c/$connectionId/indexes': typeof CConnectionIdIndexesRoute
  '/c/$connectionId/keys': typeof CConnectionIdKeysRoute
  '/c/$connectionId/overview': typeof CConnectionIdOverviewRoute
  '/c/$connectionId/tasks': typeof CConnectionIdTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/c/$connectionId'
    | '/c/$connectionId/dumps'
    | '/c/$connectionId/indexes'
    | '/c/$connectionId/keys'
    | '/c/$connectionId/overview'
    | '/c/$connectionId/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/c/$connectionId'
    | '/c/$connectionId/dumps'
    | '/c/$connectionId/indexes'
    | '/c/$connectionId/keys'
    | '/c/$connectionId/overview'
    | '/c/$connectionId/tasks'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/c/$connectionId'
    | '/c/$connectionId/dumps'
    | '/c/$connectionId/indexes'
    | '/c/$connectionId/keys'
    | '/c/$connectionId/overview'
    | '/c/$connectionId/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  CConnectionIdRoute: typeof CConnectionIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$connectionId': {
      id: '/c/$connectionId'
      path: '/c/$connectionId'
      fullPath: '/c/$connectionId'
      preLoaderRoute: typeof CConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$connectionId/dumps': {
      id: '/c/$connectionId/dumps'
      path: '/dumps'
      fullPath: '/c/$connectionId/dumps'
      preLoaderRoute: typeof CConnectionIdDumpsRouteImport
      parentRoute: typeof CConnectionIdRoute
    }
    '/c/$connectionId/indexes': {
      id: '/c/$connectionId/indexes'
      path: '/indexes'
      fullPath: '/c/$connectionId/indexes'
      preLoaderRoute: typeof CConnectionIdIndexesRouteImport
      parentRoute: typeof CConnectionIdRoute
    }
    '/c/$connectionId/keys': {
      id: '/c/$connectionId/keys'
      path: '/keys'
      fullPath: '/c/$connectionId/keys'
      preLoaderRoute: typeof CConnectionIdKeysRouteImport
      parentRoute: typeof CConnectionIdRoute
    }
    '/c/$connectionId/overview': {
      id: '/c/$connectionId/overview'
      path: '/overview'
      fullPath: '/c/$connectionId/overview'
      preLoaderRoute: typeof CConnectionIdOverviewRouteImport
      parentRoute: typeof CConnectionIdRoute
    }
    '/c/$connectionId/tasks': {
      id: '/c/$connectionId/tasks'
      path: '/tasks'
      fullPath: '/c/$connectionId/tasks'
      preLoaderRoute: typeof CConnectionIdTasksRouteImport
      parentRoute: typeof CConnectionIdRoute
    }
  }
}

interface CConnectionIdRouteChildren {
  CConnectionIdDumpsRoute: typeof CConnectionIdDumpsRoute
  CConnectionIdIndexesRoute: typeof CConnectionIdIndexesRoute
  CConnectionIdKeysRoute: typeof CConnectionIdKeysRoute
  CConnectionIdOverviewRoute: typeof CConnectionIdOverviewRoute
  CConnectionIdTasksRoute: typeof CConnectionIdTasksRoute
}

const CConnectionIdRouteChildren: CConnectionIdRouteChildren = {
  CConnectionIdDumpsRoute: CConnectionIdDumpsRoute,
  CConnectionIdIndexesRoute: CConnectionIdIndexesRoute,
  CConnectionIdKeysRoute: CConnectionIdKeysRoute,
  CConnectionIdOverviewRoute: CConnectionIdOverviewRoute,
  CConnectionIdTasksRoute: CConnectionIdTasksRoute,
}

const CConnectionIdRouteWithChildren = CConnectionIdRoute._addFileChildren(
  CConnectionIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  CConnectionIdRoute: CConnectionIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
